name: deploy-uat

on:
  push:
    branches:
      - deploy-uat
    paths:
      - README.md
      - yarn.lock
      - manifests/**
      - src/**
      - test/**
      - ./*.json
      - db/**
      - yarn.lock
      - Dockerfile
      - .npmrc
      - .github/workflows/deploy-uat.yml
      - .github/workflows/job-pr-dev.yml
      - ".github/containerscan/.trivyignores"

job:
  prdev:
    uses: ./.github/workflows/job-pr-dev.yml
